easy_admin:
    entities:
        User:
            class: App\Entity\User
            form:
                fields:
                    - {property: 'email'}
            list:
                actions:
                    - {name: 'edit', icon: 'pencil'}
                    - {name: 'delete', icon: 'trash'}